name: Build and Test Docker Image
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build -t apache-exporter .

      - name: Test Docker image
        run: |
          docker run --rm apache-exporter --version

          #      - name: Login to Docker Hub
          #        uses: docker/login-action@v1
          #        with:
          #          username: ${{ secrets.DOCKERHUB_USERNAME }}
          #          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          #
          #      - name: Push Docker image to Docker Hub
          #        uses: docker/build-push-action@v2
          #        with:
          #          context: .
          #          push: true
          #          tags: my-docker-image:latest
          #
